### ISSUE TITLE
making code in pdf look abit better?

### ISSUE THREAD

**Issue by shirshak55** [driade/laravel-book#10]
Yea pdfs are already good but I think we can make code look a bit nice and add background etc. Do you use bash scripts to convert markdown to pdf?

**Comment by driade** [comment]
Hi, thanks for the feedback.

No, PDFs are created from the epub, which is made by code. Could you provide some example of how the code could get better?

**Comment by shirshak55** [comment]
@driade  Please find example attached.
<img width="970" alt="screen shot 2018-08-16 at 8 29 01 pm" src="https://user-images.githubusercontent.com/8097377/44215799-1d619900-a193-11e8-9d17-0db1d23ab216.png">

**Comment by driade** [comment]
May you review this one?

[laravel-docs-5.0.pdf](https://github.com/driade/laravel-book/files/2294918/laravel-docs-5.0.pdf)

**Comment by driade** [comment]
Please let me check. At this moment the PDF is just an exact version of the docs, with just a few small adaptations to make it look enough good. Your suggestion is great but it may need a lot of code and testing to be sure everything looks as expected.

The only way I suppose this could be done in a reasonable time is open sourcing the code of this project :) I don't know if I'm ready for that, some parts of it are a bit "ugly" an were never intended to be "shown" to the outer world. For example, the current code lacks of tests.

**Comment by shirshak55** [comment]
may be if you release code somebody will PR it and we can improve styles etc too :D
