### ISSUE TITLE
Lumen too?

### ISSUE THREAD

**Issue by HenkPoley** [driade/laravel-book#11]
It would be cool if you could run the [Lumen](https://lumen.laravel.com/) docs as epub/pdf/mobi as well. It's basically the core of Laravel. So it ought to be pretty similar.

* https://lumen.laravel.com/docs/5.8
* https://github.com/laravel/lumen-docs

**Comment by driade** [comment]
Of course.

May you please proofread the files at https://github.com/driade/laravel-lumen-book ?

Thanks!

**Comment by HenkPoley** [comment]
Sweet, I'll put it on my Kobo 👍

**Comment by HenkPoley** [comment]
It's more of a bug report for both, but could you put `white-space: pre-wrap;` on the code style? So long source code lines don't go outside the border of the screen.

https://github.com/paulwellnerbou/epub-styles

**Comment by HenkPoley** [comment]
Okay, I've read through the document. No further problems, apart from maybe wanting to have some kind of syntax highlighting. But I think that would be hard to pull off on a limited greyscale screen.

I think I would vaguely like it if all the referenced Laravel documentation would be included as well, but I don't think that's a blocker. Also, it might be hard to automate, what to include and what not.
