### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by Mohamed4Dev** [driade/laravel-book#13]
Font size is too small in pdf printed version.
Can you please make a version for print? or how can I edit on _.epub_ version? if it is editable format.

**Comment by driade** [comment]
Hello. You're right, maybe the font size is small on PDF.

I've updated the code to generate PDFs with font size 14 instead of 12; already uploaded. Do you think it's better now?

Also, you can convert an epub to PDF with programs like Calibre. It may let you adjust the font size at your will.

**Comment by Mohamed4Dev** [comment]
Great, thanks.
