### ISSUE TITLE
laravel-docs-8.x.epub, mobi and pdf are missing a part of Blade Templates section

### ISSUE THREAD

**Issue by jakubgg** [driade/laravel-book#14]
The docs for Laravel 8.x (version updated on 4 Oct 2021) all (epub, mobi, pdf) are missing a chunk of Blade Templates section. 
The text is cut off after "The @verbatim Directive" first paragraph and jumps into the middle of "Reserved Keywords" section (the list of reserved keywords). It's page 111 in PDF version of the docs.

**Comment by driade** [comment]
Thanks, a poorly written regular expression broke the rendering.

It's fixed in 8.x and now I'm uploading all the docs for if any other has the same error.
