### ISSUE TITLE
Some sections in PDF could be improved

### ISSUE THREAD

**Issue by joseborges** [driade/laravel-book#15]
Hi

First of all thanks for your work.

I noticed that on version 8.x (at least) some sections are not imported correctly to PDF (hyperlinked that is). 

Example: (page 225)

[all](#method-all) [average](#method-average) [avg](#method-avg) [chunk](#method-chunk) [chunkWhile]
(#method-chunkwhile) [collapse](#method-collapse) [collect](#method-collect) [combine](#method-combine)
[concat](#method-concat) [contains](#method-contains) [containsStrict](#method-containsstrict) [count]
(#method-count) [countBy](#method-countBy) [crossJoin](#method-crossjoin) [dd](#method-dd) [diff]
(#method-diff) [diffAssoc](#method-diffassoc) [diffKeys](#method-diffkeys) [dump](#method-dump)
[duplicates](#method-duplicates) [duplicatesStrict](#method-duplicatesstrict) [each](#method-each)
[eachSpread](#method-eachspread) [every](#method-every) [except](#method-except) [filter](#method-filter)
[first](#method-first) [firstWhere](#method-first-where) [flatMap](#method-flatmap) [flatten](#method-flatten)
[flip](#method-flip) [forget](#method-forget) [forPage](#method-forpage) [get](#method-get) [groupBy]
(#method-groupby) [has](#method-has) [implode](#method-implode) [intersect](#method-intersect)
[intersectByKeys](#method-intersectbykeys) [isEmpty](#method-isempty) [isNotEmpty](#method-isnotempty)
[join](#method-join) [keyBy](#method-keyby) [keys](#method-keys) [last](#method-last) [macro](#methodmacro)
[make](#method-make) [map](#method-map) [mapInto](#method-mapinto) [mapSpread](#methodmapspread)
[mapToGroups](#method-maptogroups) [mapWithKeys](#method-mapwithkeys) [max](#methodmax)
[median](#method-median) [merge](#method-merge) [mergeRecursive](#method-mergerecursive) [min]
(#method-min) [mode](#method-mode) [nth](#method-nth) [only](#method-only) [pad](#method-pad)
[partition](#method-partition) [pipe](#method-pipe) [pipeInto](#method-pipeinto) [pluck](#method-pluck)
[pop](#method-pop) [prepend](#method-prepend) [pull](#method-pull) [push](#method-push) [put](#methodput)
[random](#method-random) [range](#method-range) [reduce](#method-reduce) [reduceSpread](#methodreduce-
spread) [reject](#method-reject) [replace](#method-replace) [replaceRecursive](#methodreplacerecursive)
[reverse](#method-reverse) [search](#method-search) [shift](#method-shift) [shuffle]
(#method-shuffle) [sliding](#method-sliding) [skip](#method-skip) [skipUntil](#method-skipuntil) [skipWhile]
(#method-skipwhile) [slice](#method-slice) [sole](#method-sole) [some](#method-some) [sort](#method-sort)
[sortBy](#method-sortby) [sortByDesc](#method-sortbydesc) [sortDesc](#method-sortdesc) [sortKeys]
(#method-sortkeys) [sortKeysDesc](#method-sortkeysdesc) [splice](#method-splice) [split](#method-split)
[splitIn](#method-splitin) [sum](#method-sum) [take](#method-take) [takeUntil](#method-takeuntil)
[takeWhile](#method-takewhile) [tap](#method-tap) [times](#method-times) [toArray](#method-toarray)
[toJson](#method-tojson) [transform](#method-transform) [union](#method-union) [unique](#method-unique)
[uniqueStrict](#method-uniquestrict) [unless](#method-unless) [unlessEmpty](#method-unlessempty)
[unlessNotEmpty](#method-unlessnotempty) [unwrap](#method-unwrap) [values](#method-values) [when]
(#method-when) [whenEmpty](#method-whenempty) [whenNotEmpty](#method-whennotempty) [where]
(#method-where) [whereStrict](#method-wherestrict) [whereBetween](#method-wherebetween) [whereIn]
(#method-wherein) [whereInStrict](#method-whereinstrict) [whereInstanceOf](#method-whereinstanceof)
[whereNotBetween](#method-wherenotbetween) [whereNotIn](#method-wherenotin) [whereNotInStrict]
(#method-wherenotinstrict) [whereNotNull](#method-wherenotnull) [whereNull](#method-wherenull) [wrap]
(#method-wrap) [zip](#method-zip)

These should be link to the proper "methods" on the pdf page, is this possible?

![image](https://user-images.githubusercontent.com/7250506/145549178-8a809a9a-8100-4653-a8f6-ca7a6ab8aba6.png)

**Comment by driade** [comment]
Thanks! I've checked and yes, many parts where completely wrong. I've switched the markdown renderer to the same used in Laravel's website and it seems it has fixed this issue - and probably other ones-.

May you please check too and tell me it you anything else wrong?

**Comment by josealgardataborges** [comment]
> Hi
> 
> First of all thanks for your work.
> 
> I noticed that on version 8.x (at least) some sections are not imported correctly to PDF (hyperlinked that is).
> 
> Example: (page 225)
> 
> [all](#method-all) [average](#method-average) [avg](#method-avg) [chunk](#method-chunk) [chunkWhile] (#method-chunkwhile) [collapse](#method-collapse) [collect](#method-collect) [combine](#method-combine) [concat](#method-concat) [contains](#method-contains) [containsStrict](#method-containsstrict) [count] (#method-count) [countBy](#method-countBy) [crossJoin](#method-crossjoin) [dd](#method-dd) [diff] (#method-diff) [diffAssoc](#method-diffassoc) [diffKeys](#method-diffkeys) [dump](#method-dump) [duplicates](#method-duplicates) [duplicatesStrict](#method-duplicatesstrict) [each](#method-each) [eachSpread](#method-eachspread) [every](#method-every) [except](#method-except) [filter](#method-filter) [first](#method-first) [firstWhere](#method-first-where) [flatMap](#method-flatmap) [flatten](#method-flatten) [flip](#method-flip) [forget](#method-forget) [forPage](#method-forpage) [get](#method-get) [groupBy] (#method-groupby) [has](#method-has) [implode](#method-implode) [intersect](#method-intersect) [intersectByKeys](#method-intersectbykeys) [isEmpty](#method-isempty) [isNotEmpty](#method-isnotempty) [join](#method-join) [keyBy](#method-keyby) [keys](#method-keys) [last](#method-last) [macro](#methodmacro) [make](#method-make) [map](#method-map) [mapInto](#method-mapinto) [mapSpread](#methodmapspread) [mapToGroups](#method-maptogroups) [mapWithKeys](#method-mapwithkeys) [max](#methodmax) [median](#method-median) [merge](#method-merge) [mergeRecursive](#method-mergerecursive) [min] (#method-min) [mode](#method-mode) [nth](#method-nth) [only](#method-only) [pad](#method-pad) [partition](#method-partition) [pipe](#method-pipe) [pipeInto](#method-pipeinto) [pluck](#method-pluck) [pop](#method-pop) [prepend](#method-prepend) [pull](#method-pull) [push](#method-push) [put](#methodput) [random](#method-random) [range](#method-range) [reduce](#method-reduce) [reduceSpread](#methodreduce- spread) [reject](#method-reject) [replace](#method-replace) [replaceRecursive](#methodreplacerecursive) [reverse](#method-reverse) [search](#method-search) [shift](#method-shift) [shuffle] (#method-shuffle) [sliding](#method-sliding) [skip](#method-skip) [skipUntil](#method-skipuntil) [skipWhile] (#method-skipwhile) [slice](#method-slice) [sole](#method-sole) [some](#method-some) [sort](#method-sort) [sortBy](#method-sortby) [sortByDesc](#method-sortbydesc) [sortDesc](#method-sortdesc) [sortKeys] (#method-sortkeys) [sortKeysDesc](#method-sortkeysdesc) [splice](#method-splice) [split](#method-split) [splitIn](#method-splitin) [sum](#method-sum) [take](#method-take) [takeUntil](#method-takeuntil) [takeWhile](#method-takewhile) [tap](#method-tap) [times](#method-times) [toArray](#method-toarray) [toJson](#method-tojson) [transform](#method-transform) [union](#method-union) [unique](#method-unique) [uniqueStrict](#method-uniquestrict) [unless](#method-unless) [unlessEmpty](#method-unlessempty) [unlessNotEmpty](#method-unlessnotempty) [unwrap](#method-unwrap) [values](#method-values) [when] (#method-when) [whenEmpty](#method-whenempty) [whenNotEmpty](#method-whennotempty) [where] (#method-where) [whereStrict](#method-wherestrict) [whereBetween](#method-wherebetween) [whereIn] (#method-wherein) [whereInStrict](#method-whereinstrict) [whereInstanceOf](#method-whereinstanceof) [whereNotBetween](#method-wherenotbetween) [whereNotIn](#method-wherenotin) [whereNotInStrict] (#method-wherenotinstrict) [whereNotNull](#method-wherenotnull) [whereNull](#method-wherenull) [wrap] (#method-wrap) [zip](#method-zip)
> 
> These should be link to the proper "methods" on the pdf page, is this possible?
> 
> ![image](https://user-images.githubusercontent.com/7250506/145549178-8a809a9a-8100-4653-a8f6-ca7a6ab8aba6.png)

Yeap! It's working now. Thanks!

The only issue I found is this (but this is minor):
![image](https://user-images.githubusercontent.com/8929655/145846706-e9e73baa-242c-4949-9f6f-881c72e8f817.png)

**Comment by josealgardataborges** [comment]
This is minor, just reporting should you be able to fix it.

**Comment by driade** [comment]
Thanks @joseborges !

I don't think I'm able to fix that late rendering error, it's not really i, my hands.
