### ISSUE TITLE
Question about styling in ePub

### ISSUE THREAD

**Issue by stefanos82** [driade/laravel-book#16]
Sincere question: what is the technical problem to use the existing style (CSS) of Laravel documentation in ePub?

It's quite appealing and pleasing to the eye in contrast to plain text...well, at least with code examples that is.

**Comment by driade** [comment]
Good morning, thanks.

As far as I understand the current appearance of code in Laravel's docs comes from some kind of code preprocessing from php to the final css. I don't now how they do it now.

I'll check ;)

**Comment by stefanos82** [comment]
I have found it; it's mentioned in footer area.

![image](https://user-images.githubusercontent.com/1777466/166147692-54226698-cbe3-4c8d-8ec0-874c75675178.png)

https://torchlight.dev/

I guess they use this (?) https://torchlight.dev/docs/clients/laravel

**Comment by driade** [comment]
Thanks. I'll check if I can transform the code chunks with this prior to embed the code in the epubs.

**Comment by driade** [comment]
Hi, good night.

I haven't found any way to improve the display of the code without the use of JS.

As the epubs (the main source of the books) are created with plain HTML, it's not possible at this moment to accomplish this.

Thanks.
