### ISSUE TITLE
missing Laravel Breeze

### ISSUE THREAD

**Issue by mkantonio** [driade/laravel-book#17]
Hello
Apparently the Breeze package is missing, I already checked the "**master**" branch and "**v9**" version pdf, and in both it shows that the file is missing.
thanks you

**Comment by driade** [comment]
May you please help me? I can't find where the problem is. I can see the Breeze section on the PDF.

<img width="807" alt="Captura de pantalla 2022-07-05 a las 22 20 01" src="https://user-images.githubusercontent.com/5692232/177409584-e63d8148-1b5d-4a67-afc6-8a2444d36565.png">

**Comment by mkantonio** [comment]
Hi
I mean "Laravel Breeze" pages are missing on page 723 of the PDF, i checked also in the "epub, mobi" files and those pages are also missing.
Section Packages [page 723] -> Breeze [page 723].
Screenshot pdf.
![image](https://user-images.githubusercontent.com/39425186/179031534-6372dd9a-66f9-4b99-9d55-a35820f04611.png)
Sorry my little english, thank you for your time

**Comment by driade** [comment]
Thanks @mkantonio I'll check.
