### ISSUE TITLE
Add page numbers to TOC

### ISSUE THREAD

**Issue by abdallahalsamman** [driade/laravel-book#18]
![Screenshot_2024-03-30-12-56-31-162_com.google.android.apps.docs.jpg](https://github.com/driade/laravel-book/assets/12014839/f73467b6-bdc3-43ff-a217-1521879369cf)

TOC has no page numbers, I want to print the book but it would be difficult for me to navigate it without numbers in TOC

**Comment by driade** [comment]
Hi. Sorry, this would be really complicated as the pdf version is created on the fly from the epub. We cannot know in advance the number of the page that each section will have.
