### ISSUE TITLE
Sequences not parsed on .mobi 

### ISSUE THREAD

**Issue by kolmogorov42** [driade/laravel-book#9]
Hi, I'm a Kindle Paperwhite owner.

I noticed that, consistently in the text, sequences such as `{tip}` are not rendered (an icon should be present, perhaps?) and left as-is.

Might be something to fix in an otherwise excellent version. The typesetting is actually good, unlike most .mobi books I've read! 🍻

**Comment by driade** [comment]
Thanks for pointing that out. I've already uploaded new versions with that error corrected.
